site_name: 'Ofimática y archivo de documentos'

nav:
  - Inicio: index.md
  - Tema 1 - Información a través de la red: 01-redes.md
  - Tema 2 - Comunicaciones internas y externas: 02-comunicaciones.md
  - Tema 3 - Procesadores de texto: 03-procesadores.md
  - Tema 4 - Hojas de cálculo: 04-excel.md
  - Tema 5 - Presentaciones PPT: 05-ppt.md
  - Tema 6 - Reprografía: 06-reprografia.md
  # - Tema 7 - Encuadernación: 07-encuadernacion.md


theme:
  name: material

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'teal'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: 'teal'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Inter
  
  language: es
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top

    - header.autohide
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox
  - search